### ISSUE TITLE
Exact Match Letters Auto-fill

### ISSUE THREAD

**Issue by copperkiddx** [bbbbbr/gb-wordle#2]
An idea for a new feature: Auto-fill any green letters on the active row to save the player from typing the entire word in each time. This would be incredibly helpful. Thanks for your consideration and your excellent work!

**Comment by bbbbbr** [comment]
I added a cursor for the board, so this is on the way soon too. 

Would you be up for testing + some feedback about the board cursor?

I think I have the usability mostly dialed in, but it could use more eyes on it before wider release.

**Comment by copperkiddx** [comment]
Absolutely! If you want to contact me, my email is copperkiddx@gmail.com

**Comment by bbbbbr** [comment]
### OK this is the latest build (includes lots of different languages):
  - [GBWORDYL_0.78_GB-and-Pocket_DE_EN_ES_FR_IT_NL_LA.zip](https://github.com/bbbbbr/gb-wordle/files/8310292/GBWORDYL_0.78_GB-and-Pocket_DE_EN_ES_FR_IT_NL_LA.zip)

### Here's the current changelist trimmed to what's relevant for this ticket (a lot has changed internally):
  - Added: Hard mode (Must use all exact match letters in same location and all  wrong-location letters)
  - Added: Moveable Board letter cursor (active letter box is dashed)
    - Move Left: SELECT + B
    - Move Right: SELECT + A
  - Added: Auto-fill exact matched letters from previous guess: SELECT + START (can be pressed multiple times)
  - Changed: 3 x SELECT to open in-game menu now (to reduce accidental menu opening)

With all the UI changes it may take a bit to re-acclimate. I tried to make them as non-intrusive as possible.

## The main questions are:
(answer as many or few as you want)

### Auto-Fill exact matches:
* Is the auto-fill hotkey (SELECT + START) sufficient or is a full-on option necessary?
  * (Why it matters: Menu is low on available keys and ROM space is getting low)
* Should auto-fill clear non-matched letters if they are set?

### Cursor:
* Is the cursor and it's controls sufficiently intuitive? Are the key combos workable?
* Currently overwrite of existing chars under cursor is turned off (requires delete char then add).
  * Is it non-intuitive to have to delete?
  * Or is it better to require delete to in order to avoid accidental letter overwrites?
* Is the cursor highlighting strong enough?
  * I tried to balance making it noticeable with not making it distracting (larger ones felt more intrusive)
  * I tried it on unmodded GB Pocket and GB Color and it's ok, but might be too subtle. Looks fine on GBBoy Colour and Analog Pocket

**Comment by copperkiddx** [comment]
Oh man, I CANNOT wait to try this! Thank you so much. I will test the heck out of this and get back to you ASAP.

**Comment by copperkiddx** [comment]
Wow. I played this a lot tonight and the changes are fantastic! Here are my thoughts:

The most important thing for me right off the bat is this: Once activated, correctly placed letters on the active line should have a green background instead of white. This would help my brain _immensely_.

**Regarding auto-fill**

I do like having SEL+START as the auto-fill hotkey, it works quite well. However, I do think that I would prefer having auto-fill be the default, with SEL+START clearing the auto-fill. It's hard to say which way would be better without actually testing both scenarios, but I would be happy with either one as long as the auto-filled characters have a green background.

If auto-fill is off by default (as it currently is), then enabling auto-fill should probably not clear non-matched letters if they were already set by the player.

**Regarding the cursor**

- The key combos are good and I got used to them very quickly.

- The cursor highlighting looks just right to me.

- I really think that the cursor on the active line should begin on the first unsolved letter space. For example, if the word you chose is **SHINE** and the first two letters **SH** are correct, the cursor should auto-jump to the third letter position.

(I believe this is what you mean by overwrite) If you use SEL+B to back up to a letter and then press A on the new letter that you want to use, it does not overwrite the existing letter, it just advances to the next space. It would be great to be able to simply overwrite the existing letter with the new letter that you choose. 

**Random thoughts**

- The faded letters on the top board look great and are super helpful at a glance

- Regarding incorrect alphabet letters at the bottom, they might look better if:

1. The pink background was a darker shade of red and the letter itself was white, or
2. The background was black and the letter itself was white, or
3. The incorrect letters were deleted from the alphabet altogether

Cannot wait for the next build! Thanks again for this, it's so great.

**Comment by copperkiddx** [comment]
Perhaps auto-fill without having to press SEL+START to activate it could be its own separate mode (like Hard Mode). Then you could still have the option to auto-fill in the regular mode with SEL+START if you wanted to. That might be the ideal.

**Comment by bbbbbr** [comment]
Yep- haven't pushed it yet but I now have a WIP where it is a global mode setting option in addition to the key combo. More updates coming soonish. :)

**Comment by bbbbbr** [comment]
Great feedback. A bunch of your comments I've been thinking about, but was unsure if they would be suitable for others. 
 
 (Also includes updated German UI translations from skite2001)

  - Auto-fill: Colorize copied letters to green (exact match)
  - Auto-fill: Set cursor to left-most unfilled letter after filling
  - Auto-fill: Add menu option to turn on/off automatic auto-fill
 
 - Tile flip animation is ON for manual auto-fill and OFF for automatic auto-fill.
   - The animation is a helpful indicator that an action is being performed on manual copy-down. However I turned it off  for automatic auto-fill since it seemed to blur the line between the revealed guess result and the subsequent copy-down of matched letters in a slightly disorienting way.
   - I could also turn the animation OFF for manual copy down if it's distracting there too.

CGB Keyboard Coloring
  - I tried a bunch of different variations (see image). Faded grey on white _looked_ the most chill and pleasing, but in use I found that red on pink was most helpful for avoiding non-matched characters while still being a little less stark than black on pink. This could be idiosyncratic to me.
  - Since some people will play in non-hard mode with a style that uses non-matched letters those colors still need to remain easily visible (including on non-backlit original CGB hardware - same goes for the faded board letters, I'd make those 25% lighter but then they're hard to see on original CGB)
  - If there is a future expanded version it could be pretty easy to make that customizable.

Bug Fixes:
- Fix: If player was not using hard mode then the preceding line was not guaranteed to carry all exact matches, so auto-fill might be incomplete


![not-in-word-color-options](https://user-images.githubusercontent.com/8322401/159385994-be4b9676-5844-490a-af82-0f5d67133a00.png)

**New Build:**
[GBWORDYL_0.79_GB-and-Pocket_DE_EN_ES_FR_IT_NL_LA.zip](https://github.com/bbbbbr/gb-wordle/files/8320022/GBWORDYL_0.79_GB-and-Pocket_DE_EN_ES_FR_IT_NL_LA.zip)

**Comment by copperkiddx** [comment]
YES! You've nailed it! Bravo. I had a blast playing this tonight. There is only one thing I would change now and I would play this version forever: In auto-fill mode, I would ask that green letters be skipped right over with the cursor (moving both forwards and backwards), making the green letters completely static and "unselectable" (since they never need to be changed). Again, this update is amazing.

**Comment by bbbbbr** [comment]
That's a good point (for hard mode) - I'll log that request for later if there's room left. In the mean time it will at least auto-skip forward (one tile at a time) if you press "add a letter" when you're on them. Not for delete though.

**Comment by copperkiddx** [comment]
Ok very good, I will keep my fingers crossed! Thanks again

**Comment by bbbbbr** [comment]
**Skip-Auto-Filled**
- Letter Entry/Removal will skip over any letters that have been auto-filled
- SEL + A/B Cursor will not skip over auto-filled letters
- Auto-filled letters that have been deleted will revert to normal entry behavior

**Other things to look out for**
- Any changes to settings that were not user-initiated (stats and settings now persist in SRAM/Flash)
- Quirks or bugs in menu behavior (A selects, B exits menu regardless of location, UP/DOWN move. Hard mode is a special case option in the menu since it needs to only activate before first guess is entered)
- Incorrect answer words, or valid words incorrectly rejected (There have been a ton of changes to dictionary compression since last official release)

[gb-wordyl_0.90_mbc5_en_2022_05_13_skip_autofilled.gb.zip](https://github.com/bbbbbr/gb-wordle/files/8693579/gb-wordyl_0.90_mbc5_en_2022_05_13_skip_autofilled.gb.zip)
